### ISSUE TITLE
0.4.1 Unexpected token =

### ISSUE THREAD

**Issue by iliqportals** [cyberdummy/gulp-composer#11]
Newest build has an error

Unexpected token =
Stack:
node_modules\gulp-composer\index.js:34
```
output_lines = = output.replace(/^\s+|\s+$/, '').split(/[\n\r]+/); // Trims the output and returns it split into
```

Thank you for your time!

**Comment by julienV** [comment]
i confirm... got that one too

**Comment by chishiuanlu** [comment]
Got that, too...

**Comment by cyberdummy** [comment]
Sorry I suck, should be fixed.

**Comment by julienV** [comment]
don't beat yourself up ;)
