### ISSUE TITLE
Could not open input file: php

### ISSUE THREAD

**Issue by jamie-studyportals** [cyberdummy/gulp-composer#13]
The latest version of gulp-composer is not working for us. We get the following error:

> Error in plugin 'gulp-composer'
> Message:
> Could not open input file: php

We only see this issue with the latest version.

**Comment by cyberdummy** [comment]
What are the options your passing in?

**Comment by cyberdummy** [comment]
Also what operating system are you using and what is the full output from gulp please.

**Comment by cyberdummy** [comment]
I believe latest release (0.4.4) should fix your issue. I suspect you were supplying a custom binary like bin: 'php /path/to/composer' and it was prefixing another php on the front.
