### ISSUE TITLE
options silent settable

### ISSUE THREAD

**Issue by evilebottnawi** [cyberdummy/gulp-composer#2]
set from options
```js
gulp.task('composer', function () {
    composer({ cwd: './php-stuff', bin: 'composer',  silent: false });
});
```

**Comment by k2s** [comment]
at least '--ignore-platform-reqs' should also be settable

**Comment by nathanbrauer** [comment]
I believe I have a fix for this in a rehaul that I'm working on:
https://github.com/Marketera/gulp-composer/

More specifically: https://github.com/Marketera/gulp-composer/commit/29969480d6a104a3546d71ecfa0acdc79ae23324

I'll send a pull request over in the next day or so.
