### ISSUE TITLE
Error when composer.phar is located in Windows directory with a space in its name

### ISSUE THREAD

**Issue by otravers** [cyberdummy/gulp-composer#7]
When using something like:

`    composer({
        "bin": "E:\04 - Code\composer.phar"
    });`

I get:

`events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: The filename, directory name, or volume label syntax is incorrect.
`

The same error occurs with forward slashes.

**Comment by cyberdummy** [comment]
Fixed in https://github.com/cyberdummy/gulp-composer/commit/be231646ebc0aa4bee43a3c1053e340559c4d2cc
