### ISSUE TITLE
composer error on Windows

### ISSUE THREAD

**Issue by xstable** [cyberdummy/gulp-composer#8]
_WINDOWS 7:_

If I run the composer-command on windows, the _php_ in front of c:/.....composer.phar is missing.
So Windows starts a popup to search the web for an Application which can handle .phar files.

php is added to the PATH-Variable and I can run php c:/...composer.phar  on cmd.exe without any Problem.
Seems the bug is inside of gulp-composer cause of missing to set the "php" in front of the composer command.

On Linux, same Script work like a charm.

**Comment by cyberdummy** [comment]
Have you tried using the bin option? Something like

```
 composer({
        "bin":          "php C:/...composer.phar"
  });
```

**Comment by xstable** [comment]
Use bin option exactly where?

**Comment by xstable** [comment]
I do set the bin-parameter, but without php in front of it.
On Linux, it works like a charm, even if there is no asignment to execute all .php-Files with php.

Strange, isn't it?
Now I set the php-prefix to the bin: Parameter and it seems to work on windows.
